POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
  "message": "http://localhost:3001 wants you to sign in with your Kaspa account:\nkaspa:qzlvshfvytskm9t4pacfq2r9rfugqdus02ese58ldxuxxv4280dvjrypvgwmc\n\nBy signing in, you agree to the terms of service localhost:3001/tos\n\nURI: localhost:3001\nVersion: 1\nChain ID: mainnet\nNonce: b71mk4scgrdvl2arc0tzz\nIssued At: 1741529403\nExpiration Time: 1741531203",
  "signature": "e1c808e566e339fc22b48d8eac8ae4468f6dfdeed2b9e9376c539bf7f67374bdc179c297d0e605ff8702312221831fef3f2c358dfd2a29113b093670eed03a0e",
  "publicKey": "03bec85d2c22e16d95750f709028651a788037907ab30cd0ff69b86332aa3bdac9",
  "address": "kaspa:qzlvshfvytskm9t4pacfq2r9rfugqdus02ese58ldxuxxv4280dvjrypvgwmc",
  "nonce": "b71mk4scgrdvl2arc0tzz",
  "expiry": 1741531203
}

POST http://localhost:3000/auth/refresh HTTP/1.1
content-type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRyZXNzIjoia2FzcGE6cXpsdnNoZnZ5dHNrbTl0NHBhY2ZxMnI5cmZ1Z3FkdXMwMmVzZTU4bGR4dXh4djQyODBkdmpyeXB2Z3dtYyIsInB1YmxpY0tleSI6IjAzYmVjODVkMmMyMmUxNmQ5NTc1MGY3MDkwMjg2NTFhNzg4MDM3OTA3YWIzMGNkMGZmNjliODYzMzJhYTNiZGFjOSIsIm5vbmNlIjoiYjcxbWs0c2NncmR2bDJhcmMwdHp6IiwiZXhwaXJ5IjoxNzQxNTMxMjAzLCJpYXQiOjE3NDE1Mjk0NjcsImV4cCI6MTc0MjEzNDI2N30.6VqcnKgU_kCnAiWkFUGSclTUtwfAU10x45JsvmwekHk"
}

GET http://localhost:3000/auth/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRyZXNzIjoia2FzcGE6cXpsdnNoZnZ5dHNrbTl0NHBhY2ZxMnI5cmZ1Z3FkdXMwMmVzZTU4bGR4dXh4djQyODBkdmpyeXB2Z3dtYyIsInB1YmxpY0tleSI6IjAzYmVjODVkMmMyMmUxNmQ5NTc1MGY3MDkwMjg2NTFhNzg4MDM3OTA3YWIzMGNkMGZmNjliODYzMzJhYTNiZGFjOSIsIm5vbmNlIjoiYjcxbWs0c2NncmR2bDJhcmMwdHp6IiwiZXhwaXJ5IjoxNzQxNTMxMjAzLCJpYXQiOjE3NDE3MDQ5NjksImV4cCI6MTc0MTcwNTg2OX0.I7p88uiLh7LSrVdCL6pT3VhvkGYQCj7qy6FEgQo1W8E




